### ISSUE TITLE
Can't add github/cmark

### ISSUE THREAD

**Issue by blackst0ne** [vfeskov/win-a-beer-react#1]
Hi there, 

I'm trying to add https://github.com/github/cmark project but beer.vfeskov.com doesn't find it. 

Could you fix it, please? :slightly_smiling_face:

**Comment by blackst0ne** [comment]
Ah, `Enter` adds, but `Ctrl` + `Enter` does not. :slightly_smiling_face:

**Comment by vfeskov** [comment]
Yep, suggestions stop showing when you bump against github rate limit (60 per hour), but you can still press Enter without relying on suggestions.
